projects:
  workflows:
    local:
      node-build:
        dependencies:
          - '@liquid-labs/sdlc-resource-babel-and-rollup'
          - '@liquid-labs/sdlc-resource-eslint'
          - '@liquid-labs/sdlc-resource-jest'
        artifacts:
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 0
            path: Makefile
            purpose: >-
              Sets up standard target vars (like 'BUILD_TARGETS') and runs
              scripts from 'make'.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 10
            path: make/10-locations.mk
            purpose: Defines the most basic locations, like the source directory.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 10
            path: make/10-resources.mk
            purpose: Locates tool executables and configuration files.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 15
            path: make/15-data-finder.mk
            purpose: >-
              Sets up vars listing test data files which will need to be copied
              under the test staging dir.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 20
            path: make/20-js-src-finder.mk
            purpose: >-
              Sets up vars listing JS files which will need to be tested and
              built.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 50
            path: make/50-specify-input-js.mk
            purpose: Builds the 'dist/specify-input.js' artifact.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 55
            path: make/55-lint.mk
            purpose: Provides lint functionality with eslint.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 55
            path: make/55-test.mk
            purpose: Provides test functionality with jest.
          - builder: '@liquid-labs/sdlc-projects-workflow-local-node-build'
            version: 1.0.0-alpha.5
            priority: 95
            path: make/95-final-targets.mk
            purpose: >-
              Sets up the final basic targets (like 'build') based on the target
              vars (like 'BUILD_TARGETS').
        config: {}
  badges:
    coverage:
      dependencies: []
      artifacts:
        - builder: '@liquid-labs/sdlc-projects-badges-coverage'
          version: 1.0.0-alpha.2
          priority: 0
          content: >-
            [![coverage:
            100%](./.readme-assets/coverage.svg)](https://github.com/liquid-labs/string-input/pulls?q=is%3Apr+is%3Aclosed)
          path: /Users/zane/playground/string-input/.readme-assets/coverage.svg
          purpose: Test coverage badge for README.md.
    github-workflow:
      dependencies: []
      artifacts:
        - builder: '@liquid-labs/sdlc-projects-badges-github-workflows'
          version: 1.0.0-alpha.2
          priority: '1'
          content: >-
            [![Unit
            tests](https://github.com/liquid-labs/string-input/actions/workflows/unit-tests-node.yaml/badge.svg)](https://github.com/liquid-labs/string-input/actions/workflows/unit-tests-node.yaml)
          purpose: Display status of 'Unit tests' GitHub Workflow.
          config: {}
