# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

.DELETE_ON_ERROR:

SHELL:=bash

default: all

PHONY_TARGETS:=all default

BUILD_TARGETS:=

DOC_TARGETS:=

LINT_TARGETS:=

TEST_TARGETS:=

ifneq ($(wildcard make/*.mk),)
include make/*.mk
endif
