# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

.PRECIOUS: $(PRECIOUS_TARGETS)

build: $(BUILD_TARGETS)

PHONY_TARGETS+=build

doc: $(DOC_TARGETS)

all: build doc

PHONY_TARGETS+=doc

lint: $(LINT_TARGETS)

lint-fix: $(LINT_FIX_TARGETS)

PHONY_TARGETS+=lint lint-fix

test: $(TEST_TARGETS)

PHONY_TARGETS+= test

qa: test lint

PHONY_TARGETS+=qa

.PHONY: $(PHONY_TARGETS)
